config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'
  resources :packages
  get '/packages/:id/label' =>'packages#label', :as => :label

end

app/models/package.rb
class Package < ActiveRecord::Base
	validates :from_name, presence: true

	validates_format_of :from_zip,
                    :with => %r{\d{5}(-\d{4})?},
                    :message => "%{value} is not a valid zipcode. Should be in the format of 12345 or 12345-1234"
                    
    validates_format_of :to_zip,
                    :with => %r{\d{5}(-\d{4})?},
                    :message => "%{value} is not a valid zipcode. Should be in the format of 12345 or 12345-1234"                
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/packages_controller.rb
require 'easypost'
EasyPost.api_key = Rails.application.secrets.EASYPOST_KEY

class PackagesController < ApplicationController
	
	def index
		redirect_to :root
	end

	def new
		@package = Package.new
	end

	def create
		@package = Package.new(package_params)

		@to_address = EasyPost::Address.create(
		  :verify => ["delivery"],
		  :name => @package.to_name,
		  :street1 => @package.to_address,
		  :city => @package.to_city,
		  :state => @package.to_state,
		  :zip => @package.to_zip,
		  :country => @package.to_country,
		  :phone => @package.to_phone
		)

		@from_address = EasyPost::Address.create(
		  :name => @package.from_name,
		  :street1 => @package.from_address,
		  :city => @package.from_city,
		  :state => @package.from_state,
		  :zip => @package.from_zip,
		  :country => @package.from_country,
		  :phone => @package.from_phone
		)

		@parcel = EasyPost::Parcel.create(
		  :width => @package.width,
		  :length => @package.length,
		  :height => @package.height,
		  :weight => @package.weight
		)

		# shipment = EasyPost::Shipment.create(
		#   :to_address => to_address,
		#   :from_address => from_address,
		#   :parcel => parcel,
		# )

		# @rates = shipment['rates']

		# shipment.buy(
		#   :rate => shipment.lowest_rate
		# )

		@verify =  @to_address.verifications
		# if @verify.delivery.success == false 
		# 	render 'new'
		# end

		# shipment.insure(amount: 100)

		# @insurance = shipment.insurance

		# @label = shipment.postage_label.label_url

		if @package.save and @verify.delivery.success
			redirect_to @package
		else
			render 'new'
		end
	end

	def show
		@package = Package.find(params[:id])

		to_address = EasyPost::Address.create(
		  :name => @package.to_name,
		  :street1 => @package.to_address,
		  :city => @package.to_city,
		  :state => @package.to_state,
		  :zip => @package.to_zip,
		  :country => @package.to_country,
		  :phone => @package.to_phone
		)

		from_address = EasyPost::Address.create(
		  :name => @package.from_name,
		  :street1 => @package.from_address,
		  :city => @package.from_city,
		  :state => @package.from_state,
		  :zip => @package.from_zip,
		  :country => @package.from_country,
		  :phone => @package.from_phone
		)

		parcel = EasyPost::Parcel.create(
		  :width => @package.width,
		  :length => @package.length,
		  :height => @package.height,
		  :weight => @package.weight
		)

		shipment = EasyPost::Shipment.create(
		  :to_address => to_address,
		  :from_address => from_address,
		  :parcel => parcel
		)

		@rates = shipment['rates']

		shipment.buy(
		  :rate => shipment.lowest_rate
		)

		# # @verify =  to_address.verifications
		# # if @verify.delivery.success == false 
			
		# # 	@verify.delivery.errors.each do |msg|
		# # 		flash[:error] = msg.message
		# # 	end
		# # end

		# # # shipment.insure(amount: 100)

		# # # @insurance = shipment.insurance

		@label = shipment.postage_label.label_url
		
		# @label = shipment.postage_label
	end

	def label 
		@package = Package.find(params[:id])

	end
	
	private 
		def package_params
			params.require(:package).permit(:from_name, :to_name, :from_address, :from_city, :from_state, :from_zip, :from_country, :from_phone, :to_name, :to_address, :to_city, :to_state, :to_zip, :to_country, :to_phone, :length, :width, :height, :weight)
		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/helpers/states_helper.rb
module StatesHelper

def us_states
    [
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ]
end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QuickShip</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='https://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather' rel='stylesheet' type='text/css'>
    <link href='https://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css' rel='stylesheet' type='text/css'>
    <link rel="shortcut icon" href="https://cdn2.iconfinder.com/data/icons/circle-icons-1/64/sailboat-128.png"/>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
        <!-- <img class="logo", src="https://cdn2.iconfinder.com/data/icons/circle-icons-1/64/sailboat-128.png">
        <%= link_to 'QuickShip', root_path, class: 'navbar-brand' %> -->
        <a class="navbar-brand" href="/">
            <span><img src="https://cdn2.iconfinder.com/data/icons/circle-icons-1/64/sailboat-128.png"/></span>
            QuickShip
        </a>
    </div>
  </div>
</nav>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<body class='homepage'>
	<div class="container vertical-center">
	    <div class="my-header">QuickShip</div>
		 <div class="tagline">Printing shipping labels, quick and easy.
		 </div>

		<div class="my-button">
		  <%= link_to 'Print a Label', new_package_path, class: 'btn btn-primary btn-lg' %>
	  	</div>
  	</div>

</body>